name: build test for image-factory

on:
  push:
    branches: [ master ]
    paths:
      - 'imtools/image-factory/base/**'
      - 'imtools/image-factory/ioc-exec/**'
      - '.github/workflows/image-factory-test.yaml'
      - '!imtools/image-factory/**/.gitignore'
      - '!imtools/image-factory/**/README.md'
  pull_request:
    branches: [ master ]
    paths:
      - 'imtools/image-factory/base/**'
      - 'imtools/image-factory/ioc-exec/**'
      - '.github/workflows/image-factory-test.yaml'
      - '!imtools/image-factory/**/.gitignore'
      - '!imtools/image-factory/**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build images using build-and-release-default-images.sh with test
      run: |
        cd imtools/image-factory
        ./build-and-release-default-images.sh --print-log -y --test